#!/bin/bash

TARGET=.config/systemd/user/autogit.target.wants
REPO=$HOME/$TARGET
SOURCE=$HOME/Documents/autogit/autogit@.service

print_help () {
    echo "Usage: autogit CMD [ Project ]"
    echo "Management tool for \$HOME/$TARGET"
    echo ""
    echo "commands:"
    echo "    help               print this help"
    echo "    ls                 list autogit entries"
    echo "    add [ Project ]    add new autogit entry for [ Project ]"
    echo "    rm  [ Project ]    remove autogit entry [ Project ]"
}

if [ $# -eq 0 ] || [ "$1" = "help" ]; then
    print_help
    exit 0
fi

# autogit ls
if [ "$1" = "ls" ]; then
    files=($(ls $REPO))

    for file in "${files[@]}"; do
        f=$(echo "$file" | cut -d @ -f 2 | cut -d . -f 1)
        echo "$f"
    done

    exit 0
fi

# autogit add PROJECT
if [ "$1" = "add" ] && [ $# -gt 1 ]; then
    files=($(ls $REPO))

    for file in "${files[@]}"; do
        f=$(echo "$file" | cut -d @ -f 2 | cut -d . -f 1)
        if [ "$f" = "$2" ]; then
            echo "[ autogit ]: --WARNING-- autogit entry for $2 already exists"
            exit 1
        fi
    done

    ln -s $SOURCE $REPO/autogit@$2.service
    if [ $? -ne 0 ]; then
        echo "[ autogit ]: --WARNING-- linking failed for systemd unit autogit@$2.service"
        exit 1
    fi

    systemctl daemon-reload --user
    if [ $? -ne 0 ]; then
        echo "[ autogit ]: --WARNING-- systemctl daemon-reload failed" 
        exit 1
    fi

    systemctl start --user autogit@$2.service
    if [ $? -ne 0 ]; then
        echo "[ autogit ]: --WARNING-- start of systemd unit autogit@$2.service"
        exit 1
    fi

    exit 0
fi

# autogit rm PROJECT
if [ "$1" = "rm" ] && [ $# -gt 1 ]; then
    files=($(ls $REPO))

    for file in "${files[@]}"; do
        f=$(echo "$file" | cut -d @ -f 2 | cut -d . -f 1)

        # wait for file match
        if [ "$f" != "$2" ]; then
            continue
        fi

        entry=autogit@$2.service

        rm $REPO/$entry
        if [ $? -ne 0 ]; then
            echo "[ autogit ]: --WARNING-- rm of \"$entry\" failed"
            exit 1
        else
            systemctl kill --user $entry
            if [ $? -ne 0 ]; then
                echo "[ autogit ]: --WARNING-- unable to stop systemd unit \"$entry\""
                exit 1
            fi

            exit 0
        fi
    done

    echo "[ autogit ]: --WARNING-- No autogit entry \"$entry\" found"
    exit 1
fi

print_help
exit 1
