#!/bin/bash

REPO=/home/fcallies/.config/systemd/user/autogit.target.wants
SOURCE=/home/fcallies/Documents/autogit/autogit@.service

print_help () {
        echo "autogit"
        echo "    help   prints this help"
        echo "    ls     lists autogit entries"
        echo "    add    adds new autogit entry"
        echo "    rm     removes autogit entry"
}

if [ $# -eq 0 ] || [ "$1" = "help" ]; then
        print_help
        exit 0
fi

if [ "$1" = "ls" ]; then
        files=$(ls $REPO)

        for file in "${files[@]}"; do
                f=$(echo "$file" | cut -d @ -f 2 | cut -d . -f 1)
                echo "$f"
        done

        exit 0
fi

if [ "$1" = "add" ] && [ $# -gt 1 ]; then
        files=$(ls $REPO)

        for file in "${files[@]}"; do
                f=$(echo "$file" | cut -d @ -f 2 | cut -d . -f 1)
                if [ $f -eq $2 ]; then
                        echo "WARNING: autogit entry for $2 already exists"
                        exit 0
                fi
        done

        ln -s $SOURCE $REPO/autogit@$2.service
        if [ $? -ne 0 ]; then
                echo "WARNING: linking failed for systemd unit autogit@$2.service"
                exit 1
        fi

        systemctl start --user autogit@$2.service
        if [ $? -ne 0 ]; then
                echo "WARNING: start of systemd unit autogit@$2.service"
                exit 1
        fi

        exit 0
fi

if [ "$1" = "rm" ] && [ $# -gt 1 ]; then
        files=$(ls $REPO)

        for file in "${files[@]}"; do
                f=$(echo "$file" | cut -d @ -f 2 | cut -d . -f 1)
                if [ "$f" = "$2" ]; then
                        rm $REPO/autogit@$2.service
                        if [ $? -eq 0 ]; then
                                echo "autogit entry \"$2\" removed"

                                systemctl kill --user autogit@$2.service
                                if [ $? -ne 0 ]; then
                                        echo "WARNING: unable to stop systemd unit \"autogit@$2.service\""
                                        exit 1
                                fi

                                exit 0
                        fi
                        
                        echo "WARNING: autogit entry \"$2\" could not be removed"
                        exit 1
                fi
        done

        echo "WARNING: No autogit entry \"$2\" found"
        exit 0
fi

