#!/bin/bash

autogit="autogit.v2.sh"
utils="utils.sh"
store="autogit.store"

if [[ ! -f "$(pwd)/$utils" ]]; then
    echo "[ ERROR ]: utils.sh not available in $(pwd)"
    exit 1
fi

source ./utils.sh

if [[ -f $autogit ]]; then
    if [[ ! -d "$HOME/.local/bin" ]]; then
        mkdir -p "$HOME/.local/bin"
    fi
    cp $autogit "$HOME/.local/bin/autogit"
    info "installed $autogit to $HOME/.local/bin/autogit"
fi

if [[ -f $utils ]]; then
    if [[ ! -d "$HOME/.local/include" ]]; then
        mkdir -p "$HOME/.local/include"
    fi
    cp $utils "$HOME/.local/include/autogit-utils.sh"
    info "installed $utils to $HOME/.local/include/autogit-utils.sh"
fi

if [[ ! -d "$HOME/.local/etc" ]]; then
    mkdir -p "$HOME/.local/etc"
fi
touch "$HOME/.local/etc/$store"
info "installed $store to $HOME/.local/etc/$store"

which autogit &> /dev/null
rc=$?
if [[ $rc -ne 0 ]]; then
    info "add $HOME/.local/bin to PATH"
    export PATH="$HOME/.local/bin:$PATH"
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> $HOME/.bashrc
fi

systemctl link --user ./autogit-v2.service
systemctl enable --user autogit-v2.service
systemctl start --user autogit-v2.service
